### ISSUE TITLE
default import xml file

### ISSUE THREAD

**Issue by nikolauska** [headswe/Swifty#100]
#### Description
Adding default xml name like import.xml that swifty can use to make import url same as repository url. Currently we have to link directly to xml file.

#### Example
Current:
```
http://repo.clan.com/import.xml
```

Wanted:
```
http://repo.clan.com
```

**Comment by headswe** [comment]
will add in as default.xml

**Comment by headswe** [comment]
Will now do this, also you can now omit the http:// without it breaking.
