### ISSUE TITLE
Crash while updating mods

### ISSUE THREAD

**Issue by revol** [headswe/Swifty#101]
I encountered several crashes while updating diffrent mods from a repo.

while updating it just crashed without any furhter details,
but there were some eventlogs from windows that came up everytime it crashed.

The repo is: http://dhobbs.net/lambs_packs/LambsRepoUltimate
for me ace3, mbg_celle cba3 and some of the other mods produced the crash

after i updated the "big" mods by hand, all the small files (<1MB) got downloaded with no problems.
there are reports from people that didnt encountered any  crashes for the same updates with the same repo

And that are the EventLogs (Win7 x64)
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-12-08T17:16:13.000000000Z" />
    <EventRecordID>22804</EventRecordID>
    <Channel>Application</Channel>
    <Computer>localhorst</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Anwendung: Swifty.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund eines Ausnahmefehlers beendet.
Ausnahmeinformationen: System.Collections.Generic.KeyNotFoundException
Stapel:
   bei System.Windows.Forms.Control.MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)
   bei System.Windows.Forms.Control.Invoke(System.Delegate, System.Object[])
   bei SwiftUpdater.SwiftFileDownload.&lt;DownloadFile&gt;b__0(System.Object, System.Net.DownloadProgressChangedEventArgs)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   bei System.Threading.ThreadPoolWorkQueue.Dispatch()
</Data>
  </EventData>
</Event>
```

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-12-08T17:21:05.000000000Z" />
    <EventRecordID>22809</EventRecordID>
    <Channel>Application</Channel>
    <Computer>localhorst</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Swifty.exe</Data>
    <Data>2.1.1.1</Data>
    <Data>5665d206</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.1.7601.19045</Data>
    <Data>56259271</Data>
    <Data>e0434352</Data>
    <Data>000000000000b3dd</Data>
    <Data>10a0</Data>
    <Data>01d131dc83725e5b</Data>
    <Data>C:\Users\reV\AppData\Local\Swifty\app-2.1.1.1\Swifty.exe</Data>
    <Data>C:\Windows\system32\KERNELBASE.dll</Data>
    <Data>0fd98b2b-9dd0-11e5-bc5e-005056c00008</Data>
  </EventData>
</Event>
```
(sorry for the german logs, if you need them on english i can switch my system language and post them again)
if you need anymore information, let me know

**Comment by headswe** [comment]
Thanks for the report, i'l look into this.

**Comment by headswe** [comment]
Have you been seeing this anymore?

**Comment by Alextwokay** [comment]
Several of our group members have Swifty (2.1.1.1) crash when downloading our repo.
What they end up doing is restarting Swifty and continue the download and repeat that process until done.

**Comment by Liquidtracer** [comment]
Its worth mentioning that these crashes are all from a single Repo with us (me, rev and alex) being part of the same community of 30+, all these crashes (effected over half of our players on a gamenight 20+) and were reported while we used a HTTP repo but since switching to a FTP for testing we are getting almost no crashing during downloads.
This may mean a connection or access issue on our end, or a bug within the HTTP side only and its proven hard to diagnose on aerror-less crash with little feedback to go on.

Hope our info helps, you have made a great app that we hope to stick to!

**Comment by headswe** [comment]
Race condition, pretty sure it has been fixed.
