### ISSUE TITLE
Kaspersky detects trojan.win32.generic in 2.1.1 setup.exe

### ISSUE THREAD

**Issue by silvan78** [headswe/Swifty#102]
https://getswifty.net/updates/Setup.exe
fires up a warning about detection of Trojan.Win34.Genrric

Can any1 confirm that, or it's just aantivirus missfire?

**Comment by headswe** [comment]
https://www.virustotal.com/en/file/ba1583efe8f88c1f0403348d26c5d004c42b44440b6327648faefe1b64dc5e24/analysis/1449672374/

It's a false positive.
