### ISSUE TITLE
Running swifty in debug mode

### ISSUE THREAD

**Issue by silvan78** [headswe/Swifty#103]
Is there a way to run Swifty in debug mode more logs, additional info on current action? My swifty 2.1.1 crashes after downloading 11-40 files, hangs at extracting pbo's. I'm aware that these issues might not be connected with swifty itself but also with my comp (permissions, file corruption, wrong libs), repository (damaged files, not complete mos, server restrictions) or some other thingies. I would love to take a look where is crashes/hangs and see more meaningfull data, even if just for he sake of pasting it here in fedback tracker.

**Comment by headswe** [comment]
It should log them. %appdata%/swifty/swifty.log

**Comment by silvan78** [comment]
log is empty
