### ISSUE TITLE
Imported repos from 2.0.0.8 don't get their server IP's overwritten

### ISSUE THREAD

**Issue by bux578** [headswe/Swifty#106]
After installing Swifty 2.1.1.1 I've allowed Swifty to import the old repos from the 2.0.0.8 installation. We then moved our A3 server and repo location to a new server.
Switching the URL from the repo, Swifty had to download the new repo.config with a new Arma 3 server IP. Using "Join" on the repo didn't work because Arma 3 started with the old server ip (`-connect x.x.x.x`). Further investigation revealed that the IP in "%appdata%\Swifty\Settings.xml" hasn't been overwritten with the new server IP.

Probably just an edge case.

**Comment by headswe** [comment]
Typo in example from patchcreator

ServerName in the repo.config should be ServerAddress
