### ISSUE TITLE
Incomplete downloads

### ISSUE THREAD

**Issue by bux578** [headswe/Swifty#107]
![image](https://cloud.githubusercontent.com/assets/1235520/11790729/985e7472-a29d-11e5-8c11-162f10502ad3.png)

Repo URL: http://85.93.91.114/Repos/Public/

Downloaded via Swifty. No diffs when manually copying in the original files.

**Comment by nikolauska** [comment]
Same as https://github.com/headswe/Swifty/issues/95

Our fix to this was to re-download mod that was causing errors

**Comment by headswe** [comment]
Replicated and fixed.
Issue with delta patched pbos.

**Comment by bux578** [comment]
:+1:
