### ISSUE TITLE
PatchCreator locking up

### ISSUE THREAD

**Issue by Jsmuk** [headswe/Swifty#109]
Hi, we have quite a big repo (20gb-ish) and it seems when we run patchcreator everything locks up, forcing the computer to need to be turned off. This did not happen prior to the new update which added delta patching.
ATM this is making it impossible for us to use swifty.

**Comment by headswe** [comment]
No idea, used it fine on a 25gb repo.

**Comment by Jsmuk** [comment]
I meant to reply sooner - it seems to be a pretty unique hardware related
problem as running the same repo on my PC (and a server) doesn't cause
issues. I think their drive is on the way out..
