### ISSUE TITLE
[Feature Request] Repo list

### ISSUE THREAD

**Issue by cptnnick** [headswe/Swifty#11]
It would be nice to be able to pull up a list of all mods included in a repo, I like seeing what's going on.

**Comment by headswe** [comment]
Like 95% complete, also includes the ability to toggle both preset and external mods on.

**Comment by headswe** [comment]
![image](https://cloud.githubusercontent.com/assets/425212/6808449/4b88f060-d254-11e4-9942-0fff0e86c1ac.png)

**Comment by cptnnick** [comment]
:rose: 

* Can't remove external addons folder from settings UI.

* Needs restart before external addons show up under repo settings UI.

**Comment by headswe** [comment]
Cant remove it?, not sure what ya mean.

Will fix the other one tho.

**Comment by cptnnick** [comment]
I added two folders. It's not possible to remove either (say one became
obsolete).

Because of the refresh thing I thought additional mods had to be added by
their specific folder vs. their parent folder, so I also have an @modFolder
in the list.

I like how the repo settings additional mods list filters mods already in
the repo, BTW!

**Comment by headswe** [comment]
Update, already implemented a way to delete, select item and delete
