### ISSUE TITLE
Additional Documentation on Adding Repositories

### ISSUE THREAD

**Issue by firefly2442** [headswe/Swifty#112]
When adding a repository, the application asks "do you wish to import a repository with a link or create a new one?"  There doesn't seem to be much documentation on importing via a link.  What is this linking against?  Is it an HTTP link to a specific file?  I've only been able to get the "create a new repository" option to work.

**Comment by headswe** [comment]
Added http://getswifty.net/usage.html

**Comment by firefly2442** [comment]
Thank you!
