### ISSUE TITLE
Changing BattleEye=0 to 1 causes Swifty to no longer launch Arma3 properly

### ISSUE THREAD

**Issue by Rabbit994** [headswe/Swifty#114]
Steps to Reproduce:
1) Change repo.config file to have BattleEye=1 (which seems like logical setting when you want BattleEye)
2) Build Repo
3) Upload repo.srf to repository
4) Refresh repo in Swifty
5) Launch/Join button no longer seem to do anything.

**Comment by headswe** [comment]
I tried pokeing this a bit, but it seems a issue with with battleeye.

**Comment by headswe** [comment]
Fixed in 2.1.1.4
