### ISSUE TITLE
RHS Update: Crash on illegal character

### ISSUE THREAD

**Issue by bux578** [headswe/Swifty#117]
Fresh install of 2.1.1.9

Swifty.log: http://pastebin.com/WTZg9C9H

`Starting download for addons/rhs_t72/data/anim/MG_CommanderOut ? kopia.rtm_0.spd`

Happened when updating previous RHS version.

**Comment by headswe** [comment]
Do you use a linux server for making the patches?

**Comment by bux578** [comment]
No. Windows + IIS
