### ISSUE TITLE
Autocopy plugins does not seem to be working

### ISSUE THREAD

**Issue by Hannibal2210** [headswe/Swifty#118]
I have tested this with over 20 people and found that Swifty does not seem to copy Task force radio plugins to the teamspeak folder.

I have also tried this with ACRE2 with the same results.

Is there a certain folder structure that needs to be followed to make sure the autocopy works correctly?

Also how does swifty detect the default TS installation path?.

Thanks

**Comment by headswe** [comment]
Woah, sorry about missing this one.

All files that needed to be copied to the TS3 should reside in a sub-folder of the mod in question

* @myMod
  * teamspeak
    * ts3plugin.dll

Everything inside the teamspeak folder gets copied to TS3InstallFolder/plugins/

It checks all valid teamspeak registry for the path and preforms this operation on all of them.

**Comment by Hannibal2210** [comment]
Thanks for the info, I followed this method and all seems to be working.

Thanks
