### ISSUE TITLE
Error: .pbo has zero files

### ISSUE THREAD

**Issue by sn34ky** [headswe/Swifty#120]
Today I was figuring out how to set up a repository and ran into an error which you can find here: http://pastebin.com/Z4vbyar0

The mod is called Blood Mist and is located here: http://www.armaholic.com/page.php?id=19547

The mod is working correctly, and after removing it from the repo source folder patchcreator worked fine and the repo is set up.

Nice and clean app!
Hope to be able to use blood mist with it soon.

Let me know if any more information is needed.

**Comment by headswe** [comment]
I'm looking into it

**Comment by headswe** [comment]
Repackage with a proper pbo packer.
