### ISSUE TITLE
Swifty doesn't remove extra files

### ISSUE THREAD

**Issue by bux578** [headswe/Swifty#123]
Swifty: 2.1.2.2

Having two repos: Repo1 and Repo2

* Repo1: with the ace rhs compat files in the ace folder
* Repo2: without those ace rhs compat files. 

Both repos are pointing to the Arma 3 main directory.

* When checking Repo1, Swifty correctly downloads the compat pbo files.
* When checking Repo2 afterwards, Swifty doesn't recognzie the compat files that shouldn't be in the ace folder.

**Comment by bux578** [comment]
Short clip of the problem: https://youtu.be/xIAH1SLA-L0

**Comment by headswe** [comment]
Fixed , issue with caching ;)
