### ISSUE TITLE
Empty folders are not removed

### ISSUE THREAD

**Issue by gfolkersma** [headswe/Swifty#126]
When a mod(set) is removed from a repo, the pbo's are removed on the client, but the empty folders are not, making it messy, and confusing for the user.

**Comment by headswe** [comment]
Mods are never removed, at some point there will be a option to clean leftover mods.

Its a protection feature because the user might wanna keep the mod.

**Comment by gfolkersma** [comment]
I think you misunderstood me. Ofc mods (pbo files) are removed. How else would you handle an updated mod that changes a pbo filename for example. They might be in the temp folder, but that's not what I meant.

To reproduce: Download a repository as client, then update the repo by deleting an @mod folder for example. On the client, update the repo, and notice that the pbo's are gone, but the @mod folder (and other empty folders inside) are still there.

**Comment by headswe** [comment]
Mods folder should never be deleted, not sure how you managed that.

**Comment by gfolkersma** [comment]
They are not, that's the problem ;) 

Again: the old pbo's are removed correctly, if they are no longer present in the repo (on the server). If a mod is completely removed from the repo, all pbo's are correctly deleted, but the empty folders remain, which is confusing if you look at the main repo folder on your client.

**Comment by simwah** [comment]
@gfolkersma are you regenerating the repo after you delete the @mod folder?
