### ISSUE TITLE
patchcreator - generate repo delta additionally

### ISSUE THREAD

**Issue by viper4gh** [headswe/Swifty#129]
I have the role of the repo manager. If I use the patchcreator it updates directly the repository, which has to be available via HTTP or FTP. In result patchcreator have to run on the same machine where your repository is stored.
But there are cases where you want to separate it.
There is often the case that you use webspace of a provider, because of the higher upload bandwidth. My repo is 16 GB at the moment and I have 1 MBit upload bandwidth at home. Now you can calculate how long it takes to upload the full repo to the webspace on every update, because I don't have a delta.
The use of another sync tool like rsync is further a problem, because the upload to an external webspace is often possible via FTP only.
 
A FTP sync feature is maybe not possible to implement in Swifty, but maybe you can add a parameter to patchcreator where you additionally generate the changed and additional files to a separate folder inclusive the folder structure of the source (.\@mod\addons\file.pbo). Then I can upload the content of this seperate folder completely to the webspace via FTP. Deleted files is a bit tricky, but you can output it as log info of patchcreator and then I know which files I have to delete on the webspace.

**Comment by simwah** [comment]
I was dealing with this tool. Honestly i ended up just getting a cheap VPS from nfoservers and generate the repo on box using mono.
