### ISSUE TITLE
Windows Administrator rights

### ISSUE THREAD

**Issue by viper4gh** [headswe/Swifty#130]
Is there a special cause why the application needs Administrator rights to the runtime? It is a little bit annoying if the UAC pops up every time.
If I see it correct, it is a .NET application which is installed to your windows user profile. IMO these rights are not necessary.

**Comment by viper4gh** [comment]
Even for installation are IMO no Administrator rights necessary.

**Comment by Sniperhid** [comment]
This has been discussed extensively and is here to stay. Swifty exists to make the user experience easier. Users can install mods where-ever they please or teamspeak for matter (swifty can autocopy plugins). So the easy way to ensure this works for everyone is to have it use admin privileges. This will not change.
