### ISSUE TITLE
Trojan Detected

### ISSUE THREAD

**Issue by Spartachris** [headswe/Swifty#135]
Download newest version of Swifty. See virus.

**Comment by derbismarck** [comment]
https://www.virustotal.com/en/file/c253c1cf2db71868d9739cf011ef5180c475773a7b249a6984972e102d680033/analysis/1459374230/

**Comment by Sniperhid** [comment]
Unfortunately no anti-virus system is perfect and this is a false positive - http://www.howtogeek.com/180162/how-to-tell-if-a-virus-is-actually-a-false-positive/

It is beyond our control what anti-virus programs classify as viruses. I don't know what you expect us to do about this. To give you a bit more of a perspective from another development team that wrote a great article on the matter:
http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/
