### ISSUE TITLE
Option to check repositories manually on start

### ISSUE THREAD

**Issue by ToasterBR** [headswe/Swifty#139]
An option to turn on or off the initial check of repositories on app start.

While maintaining the philosophy of keeping the repositories up to date, if the user chose not check a repository on start, it would trigger a check if he clicked on play.  After the check is done and there is no downloads to make, the game would open normally. 

Also, the current option of mouse over a repository and manually click on recheck would still be present and could be used if the player wanted so.

This way, it would benefits players with more than one repository on very different servers.

**Comment by headswe** [comment]
Yes, i'l look into implementing this for the next version.

**Comment by ToasterBR** [comment]
Looking forward to this, @headswe! Thank you!

**Comment by ToasterBR** [comment]
Sorry, I closed the issue. Don't know if I was allowed to do it. Reopened.

**Comment by headswe** [comment]
Implemented, will be in next update.
