### ISSUE TITLE
-d does not delete specified mod from repo.srf file

### ISSUE THREAD

**Issue by Max255PL** [headswe/Swifty#142]
I tried deleting a mod folder from my repo by using the -d argument for Repocreator.

It succesfully removed the folder from the Repo output folder but the repo.srf file was not modified so it would still try to download said mod after.

Tested twice on Win 10, current Swifty version.

**Comment by headswe** [comment]
Yep broken
Work around for now is 
http://getswifty.net/Repocreator-workingdelete.zip
