### ISSUE TITLE
Argument Exception “Item with Same Key has already been added”

### ISSUE THREAD

**Issue by ToasterBR** [headswe/Swifty#143]
I don't believe it's a bug, but a limitation of the UNIX file system and Windows fs.

As in linux we can have both README.md and readme.md, the repocreator throws this exception when both files are in the same directory of the mod folder.

The solution is to leave only one file of the same name.

Tested on CentOS. To reproduce, just touch two files with the same name, one uppercase and another lowercase.

Thanks!

**Comment by headswe** [comment]
You are correct.
All file names are lowercased and somewhat hashed and thus conflicts like these will happen.
If you have multiple files with the same name, i'l make a point to try and make a more descriptive error message.
