### ISSUE TITLE
GUI problems

### ISSUE THREAD

**Issue by System98** [headswe/Swifty#146]
**Problem:** Misaligned GUI elements/missing icon

**Swifty version:** 2.1.3.1, 2.1.3.2, 2.1.3.3, 2.1.3.4+ (also happened in all older versions tough)

**Description:** Since I first used Swifty I always had problems with the GUI being messy in the top right corner (marked in red below). For the new version I tried uninstalling, deleting all folders left over (in Local and Roaming too) and then reinstalling several times. Unfortunatly this didn't work and the top right corner still has misaligned GUI elements. The "x" to close the program is always missing, altough when I click that empty spot Swifty _does_ close.

![swifty_gui_problem](https://cloud.githubusercontent.com/assets/16070900/15942506/fde0f6a8-2e84-11e6-8d79-453be0ea807d.jpg)

**Comment by headswe** [comment]
Big screen?

**Comment by System98** [comment]
Regular 24" in Full-HD

**Comment by Sniperhid** [comment]
Is this still an issue on the latest 2.1.4.9?

**Comment by jonpas** [comment]
@System98

**Comment by System98** [comment]
Yes, looks exactly the same for me in 2.1.4.9

**Comment by System98** [comment]
v2.1.5.0 seems to have fixed it a bit. The "x" in the top right corner is finally visible to me. The + and wrench icon still keep their green highligting after the cursor is moved away tough.

![swifty 2 1 5 0](https://cloud.githubusercontent.com/assets/16070900/22890351/612cdc68-f20c-11e6-9e2c-26b0b09d5318.jpg)

**Comment by headswe** [comment]
Thanks for the report, i will look into this after the critical issues are fixed ;)

**Comment by headswe** [comment]
@System98 Could you check in 2.1.5.1

**Comment by System98** [comment]
@headswe: Whatever you did in v2.1.5.1, it fixed it. 👍

**Comment by headswe** [comment]
Niiiiiice!
