### ISSUE TITLE
Could not find file - 2.1.3.5

### ISSUE THREAD

**Issue by TheFlyingCorpse** [headswe/Swifty#151]
We're having issues with Swifty 2.1.3.5 where it reports it cannot find a file that breaks the entire process. 
We have tried to recreate the repo without any luck.

Current workaround for us is to install the affected mod manuall in the local mod folder for Swifty client, refresh Swifty and it resolves the issue on the next refresh/download.

Repo url: http://play.nopryl.no
Local switfy (client side): C:\Swifty
File reported missing: C:\Swifty\@bozcaada\addons\bozcaada\texHeaders.bin

Log: https://bacon-monitoring.org/swifty-404-20160619.txt

**Comment by headswe** [comment]
There were issues with pbo patching in 2.1.3.5

I'l close and if it happens again create a new ticket please.
