### ISSUE TITLE
Inconsistent handling of repository URLs - 2.1.3.7

### ISSUE THREAD

**Issue by curiousinternals** [headswe/Swifty#153]
- When adding a repository, repository URLs ending in `repoinfo.srf` are not accepted.
- When editing the address of an existing repo, the URL will not be accepted without `repoinfo.srf` on the end.

**Comment by headswe** [comment]
I could replicate the first but not the second.

**Comment by curiousinternals** [comment]
It's still happening for me. Perhaps it's something specific to the URL I'm using:
https://dl.dropboxusercontent.com/u/589311510/swifty/BugQuota
