### ISSUE TITLE
HTTP Basic Auth

### ISSUE THREAD

**Issue by skarphet** [headswe/Swifty#156]
Was something changed in regards to HTTP Basic Auth this last update? We've been using it fine since the version before 2.1.4.0(and .2) but now everything is throwing a 401 when updating. I've turned it off and it seems to work fine now.

Any thoughts? I tried to change the username and pw to "a" on both the server and client to see what happens, but no change. Once it's turned off, it works.

**Comment by headswe** [comment]
Will be fixed in 2.1.4.3
