### ISSUE TITLE
Error: One or more files were not downloaded, pleas check the log

### ISSUE THREAD

**Issue by ebuc87** [headswe/Swifty#160]
When I will download the new repo update I become this error. 
"Error: One or more files were not downloaded, pleas check the log"

Here the log:
2016-10-05 18:48:04,231 [16] INFO SwiftUpdater.Pages.NDownload - Download for addons\mm_residential.pbo.EonomicLifeV2.0.bisign_0.spd faulted with Der Stapel ist leer.
System.InvalidOperationException: Der Stapel ist leer.
   bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   bei System.Collections.Generic.Stack`1.Pop()
   bei SwiftUpdater.Pages.NDownload.GetLabel()
   bei SwiftUpdater.Pages.NDownload.DownloadFile(KeyValuePair`2 data)

2016-10-05 18:48:10,894 [12] INFO SwiftUpdater.Pages.NDownload - Crash
System.Exception: One or more files were not downloaded, please check the log
   bei SwiftUpdater.Pages.NDownload.Work()
   bei SwiftUpdater.Pages.NDownload.Worker_DoWork(Object sender, DoWorkEventArgs e)

**Comment by headswe** [comment]
Fixed in 2.1.4.5
