### ISSUE TITLE
Repository over FTP

### ISSUE THREAD

**Issue by LtJulius** [headswe/Swifty#164]
If I use the "Add Repository" Button in the Swifty Menu, I can't import a second repository over FTP, only over HTTP.

**Comment by headswe** [comment]
There are no FTP capability anymore.

**Comment by coachwn** [comment]
@headswe Just found this program as a possible replacement for the ridiculously buggy Arma3Sync...in looking around I saw that FTP creation of repo was not possible anymore. May I ask why?

**Comment by jonpas** [comment]
Because FTP is antique and there is no reason to bother supporting it.

**Comment by coachwn** [comment]
@jonpas don't think my question was directed at you but thanks for your input. 

Many communities still use FTP; so why limit your connection options; is it that hard to write the code for that aspect as well? I am genuinely curious as I do not understand this side of it and want to learn about it.

**Comment by headswe** [comment]
A, 
Yes, it does require extra work.
B,
There was no free FTP library that worked correctly or supported all the functions that i wanted.
C,
Serving the files via HTTP is both easier to setup and in the correct setups faster then FTP.

If you require help with setting up a HTTP server such as Apache, nginx, IIS.
There are several guides if you google around.

Thanks.

**Comment by coachwn** [comment]
Thanks @headswe we may have to rethink a few things hosting wise. Our server is more than capable of hosting the files but we don't have it setup as an http host due to bandwidth issues since we are running 8 servers on our box at a time.

**Comment by jonpas** [comment]
I answered because I've heard the explanation before.

You can use something like [HFS](http://www.rejetto.com/hfs/) if you only need a file server, similar to how you'd setup FTP.

**Comment by headswe** [comment]
@jonpas Very cool, haven't seen that before!
