### ISSUE TITLE
Font Fixer and failed starts with Swift 2.1.5.1

### ISSUE THREAD

**Issue by PaulKeeble** [headswe/Swifty#173]
The latest version of Swifty 2.1.5.1 contains a new shortcut called font fixer and when the application launches I am seeing some sort of process storm where many many windows are constantly created and destroyed and it never completes.

Swifty is 100% broken, it can be launched.

Windows 10 latest updates not sure what else could be relevant to the problem.

**Comment by headswe** [comment]
I am aware, currently trying fix it.

**Comment by wexom** [comment]
You can stop the CMD with using admin mode cmd and then spamming "taskkill /f /im Swifty.exe"

**Comment by headswe** [comment]
`for /l %%x in (1,1,100) do taskkill /f /im Swifty.exe`
Credits to darkcharon.

**Comment by headswe** [comment]
Should be solved in 2.1.5.2

**Comment by wexom** [comment]
Fixed for me
