### ISSUE TITLE
Abort validation if play/launch is clicked

### ISSUE THREAD

**Issue by Cuel** [headswe/Swifty#177]
Feature request

I'm currently not launching with swifty due to the fact that the game can't start when files are checked (CTD w/ files in use).
The check takes around 20-30 seconds with our repo (30gb) and if there was a way to abort the validation if I select play/launch, it would be much appreciated

**Comment by headswe** [comment]
There is a checkbox under repo settings

**Comment by headswe** [comment]
Plus it should do the long checks once

**Comment by Cuel** [comment]
Ah never seen that, thanks
The long checks seems to happen every reboot
