### ISSUE TITLE
Error when creating repository 2.1.5.5

### ISSUE THREAD

**Issue by ebuc87** [headswe/Swifty#185]
When creating a repo with swifty-cli.exe, this error occurs:

C:\Users\Administrator\AppData\Local\Swifty\app-2.1.5.5\tools>swifty-cli create
"D:\MopPack Swifty\neu\Tanoa\repo" "D:\MopPack Swifty\neu\Tanoa\out"
Processing @eonomiclife - 1/2

Unbehandelte Ausnahme: System.AggregateException: Mindestens ein Fehler ist aufg
etreten. ---> System.IO.InvalidDataException: Ungültige Daten beim Decodieren ge
funden.
   bei SwiftAddon.PboHeader.ReadHeader(FileStream stream)
   bei SwiftAddon.PboHeader..ctor(FileStream stream)
   bei SwiftAddon.FileData.ProcessPbo(FileStream stream)
   bei SwiftAddon.FileData..ctor(FileInfo info, DirectoryInfo source, String add
onName)
   bei SwiftAddon.Addon.<>c__DisplayClass5_0.<.ctor>b__0(FileInfo fileInfo)
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachWorker>b_
_0(Int32 i)
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()

   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicatin
g>b__0(Object )
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCancele
dExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationT
oken cancellationToken)
   bei System.Threading.Tasks.Task.Wait()
   bei System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, In
t32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWi
thState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] a
rray, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Ac
tion`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEvery
thing, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable
`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithStat
e, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWith
Everything, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Ac
tion`1 body)
   bei SwiftAddon.Addon..ctor(String path)
   bei swifty_cli.Defines.ProcessAddons(List`1 addonfolders, String output)
   bei swifty_cli.Create.Do(List`1 args)
   bei swifty_cli.Program.Main(String[] args)

C:\Users\Administrator\AppData\Local\Swifty\app-2.1.5.5\tools>

**Comment by headswe** [comment]
It seems one of the pbo have  a malformed header,

[tools.zip](https://github.com/headswe/Swifty/files/801210/tools.zip)

Try using these tools and we might get more information.

**Comment by ebuc87** [comment]
I found the error, it was the encrypted pbos.
here the errors:

error 1:
D:\Benutzer\Administrator\Neuer Ordner\tools>swifty-cli create "D:\MopPack Swift
y\neu\Tanoa\repo" "D:\MopPack Swifty\neu\Tanoa\out"
Processing @eonomiclife - 1/2

Unbehandelte Ausnahme: System.OverflowException: Die arithmetische Operation hat
 einen Überlauf verursacht.
   bei System.Linq.Enumerable.Sum(IEnumerable`1 source)
   bei System.Linq.Enumerable.Sum[TSource](IEnumerable`1 source, Func`2 selector
)
   bei SwiftAddon.FileData.get_Length()
   bei SwiftAddon.FileData.Serialize(FileStream stream)
   bei SwiftAddon.Addon.Serialize(DirectoryInfo dir)
   bei swifty_cli.Defines.ProcessAddons(List`1 addonfolders, String output)
   bei swifty_cli.Create.Do(List`1 args)
   bei swifty_cli.Program.Main(String[] args)

D:\Benutzer\Administrator\Neuer Ordner\tools>

error 2:
D:\Benutzer\Administrator\Neuer Ordner\tools>swifty-cli create "D:\MopPack Swift
y\neu\Tanoa\repo" "D:\MopPack Swifty\neu\Tanoa\out"
Processing @eonomiclife - 1/2
Processing @eonomicmap - 2/2

Unbehandelte Ausnahme: System.AggregateException: Mindestens ein Fehler ist aufg
etreten. ---> System.ArgumentException: Ein Element mit dem gleichen Schlüssel w
urde bereits hinzugefügt.
   bei System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   bei System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Bo
olean add)
   bei System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   bei SwiftAddon.FileData.ProcessPbo(FileStream stream)
   bei SwiftAddon.FileData..ctor(FileInfo info, DirectoryInfo source, String add
onName)
   bei SwiftAddon.Addon.<>c__DisplayClass5_0.<.ctor>b__0(FileInfo fileInfo)
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachWorker>b_
_0(Int32 i)
   bei System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()

   bei System.Threading.Tasks.Task.InnerInvoke()
   bei System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   bei System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicatin
g>b__0(Object )
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCancele
dExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationT
oken cancellationToken)
   bei System.Threading.Tasks.Task.Wait()
   bei System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, In
t32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWi
thState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] a
rray, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Ac
tion`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEvery
thing, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable
`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithStat
e, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWith
Everything, Func`1 localInit, Action`1 localFinally)
   bei System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Ac
tion`1 body)
   bei SwiftAddon.Addon..ctor(String path)
   bei swifty_cli.Defines.ProcessAddons(List`1 addonfolders, String output)
   bei swifty_cli.Create.Do(List`1 args)
   bei swifty_cli.Program.Main(String[] args)

D:\Benutzer\Administrator\Neuer Ordner\tools>

**Comment by mikehudak** [comment]
```
Processing @FOW - 1/1

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at SwiftAddon.FileData.ProcessPbo(FileStream stream)
   at SwiftAddon.FileData..ctor(FileInfo info, DirectoryInfo source, String addonName)
   at SwiftAddon.Addon.<>c__DisplayClass5_0.<.ctor>b__0(FileInfo fileInfo)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] array, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at SwiftAddon.Addon..ctor(String path)
   at swifty_cli.Defines.ProcessAddons(List`1 addonfolders, String output)
   at swifty_cli.Create.Do(List`1 args)
   at swifty_cli.Program.Main(String[] args)
```

**Comment by headswe** [comment]
Duplicate of #172
