### ISSUE TITLE
Some pbos downloading at abnormally slow speeds

### ISSUE THREAD

**Issue by Djzonk** [headswe/Swifty#186]
![](http://i.imgur.com/c38uVJx.gif)
As you can see in the gif that "cup_terrains_cwa_plants.pbo" is downloading at 16 KB/s compared to the around 2 MB/s that the other pbos are downloading at. 

This happens with the same 3 pbos every time.

- cup_terrains_cwa_plants.pbo
- BornholmLayers.pbo
- BornholmObjects.pbo

happens to everyone who tries to download from my repo.

Swifty Version: 2.1.5.5

**Comment by headswe** [comment]
Could you give me a list of filzesize for the files in the images?

Thanks


Den 1 mars 2017 21:33 skrev "Daniel Jupp" <notifications@github.com>:

**Comment by Djzonk** [comment]
- cup_terrains_maps_cain: 374 MB
- cup_terrains_cwa_plants: 886 MB - Problematic
- cup_terrains_maps_eden: 390 MB
- cup_terrains_maps_noe: 274 MB
- cup_terrains_maps_noe: 274 MB

The other Problematic pbos (not in gif)
- BornholmObjects: 904 MB
- BornholmLayers: 578 MB

After you mentioned file sizes i though that could not be the problem as cup terrains core has files larger than all the problematic ones. Then I remembered that I downloaded cup terrains core from my repo back when spd were used and the files were split to be max file size of 500 MB (if i remember correctly).

I did a quick test of redownloading the 6 largest pbos that are in CUP Terrains Core and all but 1 got the issue.
- cup_terrains_ca_plants2: 501 MB - Problematic
- cup_terrains_worlds: 464 MB - Worked

So from what I figure any File larger than 500 MB gets the issue.

I would test if the issue persists with a different webhost but they aren't free.

**Comment by Djzonk** [comment]
Closing as it appears to be my host that is throttling file downloads larger than 500MB. Thanks for the help though as i never though about the files size being the problem.
