### ISSUE TITLE
Can't patch MCC and other PBOs

### ISSUE THREAD

**Issue by BrightCandle** [headswe/Swifty#190]
A number of files inside of the PBO for MCC are being flagged as having illegal names, but they are completely normal HPP files. It appears the diff patching is doing something odd and failing to download requiring the deletion of the mod locally before the new version can be downloaded.

Swifty version 2.1.5.6 client and server side

**Comment by headswe** [comment]
Logs required.

**Comment by BrightCandle** [comment]
[Swifty.log.txt](https://github.com/headswe/Swifty/files/836005/Swifty.log.txt)

Logs attached of two attempts to launch. Deleting the directory and retrying worked.

**Comment by headswe** [comment]
Illegal characters in path fixed in next version.
