### ISSUE TITLE
401 on passworded repository when referencing the repository directory

### ISSUE THREAD

**Issue by BrightCandle** [headswe/Swifty#191]
Web server is Nginx with no folder listings and protected by username and password.

With prior versions of swifty we used to have the repositories referred to by the parent folder name and it would automatically determine and use the /repo.srf. within that directory, now however its giving a 401 error. If we give swifty the full path to the repo.srf it works as you would expect. This was introduced in the 2.1.5.6 release.

Those with existing repository links seem to be able to refresh (except for the other bug we see) but one of those stopped working today and the repository had to be readded with the full path.

**Comment by headswe** [comment]
^Duplicate and fixed
