### ISSUE TITLE
Url validation in "Address" needs a web server default document 

### ISSUE THREAD

**Issue by bux** [headswe/Swifty#193]
Swifty 2.1.5.6

When adding a new client side repo and filling out the remote repo url the address field shows a validation error if the web server doesn't serve a default document. No error/warning is logged.

Adding e.g. an "index.html" file to the repo folder solves this issue.

1. In Swifty click on the "plus (+)" icon
2. In the new dialog click on "Create"
3. In the new dialog enter a name and fill out the repo url
4. The address field turns red.

Possible solution: instead check for the repo info file. (forgot the proper file name)

**Comment by BrightCandle** [comment]
These are the both routed in the same problem: https://github.com/headswe/Swifty/issues/191

**Comment by headswe** [comment]
Fixed in next version
