### ISSUE TITLE
Repo "missmatch" Error

### ISSUE THREAD

**Issue by ericinexile** [headswe/Swifty#198]
I have been stuck with this one for 2 months.  No one else in my group has the issue.  I have tried uninstalling swifty and all its associated folders (at least those I could find) and also uninstall the associated mods from ArmA.  When I reinstall Swifty and direct it to the repository web address, I instantly get the error.  Apparently I am not starting from scratch completely.

**Comment by headswe** [comment]
Sounds whatever shortcut you are using are linking the old one.
