### ISSUE TITLE
Unable to use obfuscated pbo's

### ISSUE THREAD

**Issue by LtJulius** [headswe/Swifty#199]
In consequence of the opening of pbo's we can't use swifty with a obfuscated mod.
We tried to add the map [Diyala Map](http://www.armaholic.com/page.php?id=30960) to the repository but because of the obfuscation of the mod, swifty dump it.

My question is, whether you will support a transfer of obfuscated mods in the future.

**Comment by headswe** [comment]
Sadly its likely this uses the new obfuscation that add duplicate files to the pbos rendering them impossible to properly update. Use the new disablepbodeltapatching in the repo.config

```
disablepbodeltapatching=@diyalamap
```
