### ISSUE TITLE
[Suggestion] Throttle Harddrive usage

### ISSUE THREAD

**Issue by Sniperhid** [headswe/Swifty#2]
Lots of people like leaving updaters/downloaders running in the background, but Swifty loves to use all the harddrive bandwidth! This would be a nice thing to have!

**Comment by Sniperhid** [comment]
This isnt a really that big a deal anymore as the checks are a lot faster!

**Comment by NuttyTecc** [comment]
![swiftygoingham](https://cloud.githubusercontent.com/assets/11823577/7011072/ba380528-dcae-11e4-9466-84e7d8e517d9.PNG)
I think this belongs in here. Unsure what swifty was doing at that point because it just finished updating one of the modpacks.
