### ISSUE TITLE
One or more files were not downloaded, please check the log

### ISSUE THREAD

**Issue by ojza** [headswe/Swifty#204]
I have this problem and I do not know what to do with it.
I attach partial log with error
2017-06-11 23: 38: 24,616 [18] INFO SwiftUpdater.Pages.NDownload - Download for @cup_terrains \ addons \ cup_terrains_ca_a10_dummy.pbo.cup_terrains_core-1.3.0.bisign faulted with Request suspended: Expired operation expired ..
System.Net.WebException: Request suspended: Operation expired.
   In System.Net.HttpWebRequest.GetResponse ()
   In SwiftUpdater.Pages.NDownload.DownloadFile (KeyValuePair`2 data, ProgressLabel label)
2017-06-11 23: 38: 24,639 [5] INFO SwiftUpdater.Pages.NDownload - Download failed with There have been one or more errors.
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: Request discontinued: Expiration of operation expired ..
   In System.Net.HttpWebRequest.GetResponse ()
   In SwiftUpdater.Pages.NDownload.DownloadFile (KeyValuePair`2 data, ProgressLabel label)
   In SwiftUpdater.Pages.NDownload. <> C__DisplayClass12_0. <Work> b__3 ()
   In System.Threading.Tasks.Task.Execute ()
   --- End of Trace Tray for Internal Exemption ---
---> (Inner Exception # 0) System.Net.WebException: Request suspended: Expired operation expired ..
   In System.Net.HttpWebRequest.GetResponse ()
   In SwiftUpdater.Pages.NDownload.DownloadFile (KeyValuePair`2 data, ProgressLabel label)
   In SwiftUpdater.Pages.NDownload. <> C__DisplayClass12_0. <Work> b__3 ()
   In System.Threading.Tasks.Task.Execute () <---

2017-06-11 23: 39: 12,332 [5] INFO SwiftUpdater.Pages.NDownload - Crash
System.Exception: One or more files were not downloaded, please check the log
   In SwiftUpdater.Pages.NDownload.Work ()
   In SwiftUpdater.Pages.NDownload.Worker_DoWork (Object sender, DoWorkEventArgs e)

**Comment by headswe** [comment]
The server or you is timing out. check your connection limit in the main settings or make sure the server is beefy enough to support it.
