### ISSUE TITLE
Crash when creating a repo containing Diyala Province

### ISSUE THREAD

**Issue by sn34ky** [headswe/Swifty#208]
When I try to create a repo that has Diyala Province in it, swifty-cli.exe will crash. When I remove the mod all is fine.

Version 2.2.1 is used.

**Comment by mikehudak** [comment]
use 

**disablepbodeltapatching=@diyala_map**

in repo.config file

**Comment by sn34ky** [comment]
Thanks! That worked!
In my case it was @dyiala_province.
