### ISSUE TITLE
Swifty is breaking Arma 3 controllers ... you'll have to fix this.

### ISSUE THREAD

**Issue by lennygo** [headswe/Swifty#214]
For me this is a very important part of Arma 3 flying. I have a head tracking system which yes it still is being detected and works fine in both Arma's ( swifty one and vanilla ) but when I start up my Vanilla Arma 3 it does not detect my X55 HOTAS system, not the throttle and not the Stick. This is a very big bumb since im only flying with those two and can not train without them. Not only that, yes my swifty Arma does detect them so it has to be something with swifty. Also I could start my Arma 3 with swifity without mods and stuff but normally I dont have to. I really dont wanna start swifty and then get into Arma I just want to get in with the normal launcher.

**Comment by headswe** [comment]
Swifty does not interfere with ArmA 3 operation at any level.

It simply passes the required parameters to the executable.

**Comment by lennygo** [comment]
Then I dont understand why it seems to be not working. There's cleary an Issue with Arma 3. I dont wanna sound disrespectful and everything but it has to be Swifty. I forgot adding this in my threat. I already tried reinstalling Swifty. When I had it deleted Vanilla arma recognises my Controllers. When Swifty is installed it no longer works.

I hope you can look into it.

Best Regard,

Grosse


________________________________
Von: Sebastian Nygren <notifications@github.com>
Gesendet: Sonntag, 26. November 2017 10:19
An: headswe/Swifty
Cc: lennygo; Author
Betreff: Re: [headswe/Swifty] Swifty is breaking Arma 3 controllers ... you'll have to fix this. (#214)


Swifty does not interfere with ArmA 3 operation at any level.

It simply passes the required parameters to the executable.

**Comment by headswe** [comment]
Have you tried launching the arma3.exe in admin mode?

**Comment by lennygo** [comment]
Yeah, Im reinstalling Arma 3 atm hope that fixes the Issue. If not im gonna write a ticket to Bohemia.

Best regards,

Grosse


________________________________
Von: Sebastian Nygren <notifications@github.com>
Gesendet: Sonntag, 26. November 2017 11:19
An: headswe/Swifty
Cc: lennygo; Author
Betreff: Re: [headswe/Swifty] Swifty is breaking Arma 3 controllers ... you'll have to fix this. (#214)


Have you tried launching the arma3.exe in admin mode?
