### ISSUE TITLE
Feature suggestion: Download only specific mods in repo

### ISSUE THREAD

**Issue by ShoppyCodes** [headswe/Swifty#224]
It would be great to be able to select only certain mods to download in a repo. E.g.

You have 3 mods in a repo:

Mod A
Mod B
Mod C

You wish to only download A and B, so you deselect C and do not download it at all until otherwise selected.

Currently you have to download everything even if you're not going to use it or already have it downloaded in a different name (e.g. mod_C and ModC), creating copies of potentially massive files.

I'm currently downloading over 10GB of duplicate files.

**Comment by headswe** [comment]
You should use the files provided by the repo if you wish to reuse a folder either copy it over into the new repo folder or use symlinks if the same naming standards arent applied.
