### ISSUE TITLE
[Bug/Crash] Gets stuck on checking for update

### ISSUE THREAD

**Issue by zitron-git** [headswe/Swifty#24]
1 out of 4 times it gets stuck on checking for update, no way to close, then swifty updater crashes.

**Comment by headswe** [comment]
Are you sure you are running the new version?, wolf accidently posted the wrong version without the auto updater.

**Comment by Wolfenswan** [comment]
For clarification: The old download was from dropbox and the UI was white/blue. The link has been fixed since a few weeks, is from MEGA and has the new black/green-ish UI.

**Comment by headswe** [comment]
This was a issue on my updater server, The issue also been corrected application side.
