### ISSUE TITLE
Improving User expierence

### ISSUE THREAD

**Issue by Sniperhid** [headswe/Swifty#27]
- At present whenever Swifty starts doing a task, like checking if a repo is upto date the progress bar doesn't seem to appear till it has probed the FTP network, there can quite a delay here, and the user might think they have been ignored is it possible to make Swifty display 0% pretty much as soon as it starts on the task, rather than delaying? This will prevent any confusion.

- The first check of the 1Tac modpack after a fresh install takes a minute or two at which point there are few mods that hold it up like AllInArma-Terrian Pack (7%), to a user it does feel like Swifty has stalled and there could be a problem, is there a better way to inform the user it is still doing things? (I am also using SSD here, so it should be quite fast)

**Comment by headswe** [comment]
http://i.gyazo.com/52db4b5eba22a9014a0590601d767827.mp4

Loader
