### ISSUE TITLE
If Folder is deleted manually swifty cannot be Uninstalled

### ISSUE THREAD

**Issue by Reyfin** [headswe/Swifty#35]
If the main Swifty Folder is deleted you cannot uninstall the programm.
You can run the uninstaller and it will say that it removed swifty but if you run the installer again it wants to uninstall swifty again.

**Comment by headswe** [comment]
Fixed.

**Comment by Reyfin** [comment]
Is the update pushed to the Website? Because if so then its not fixed.

**Comment by headswe** [comment]
It is not.

2015-06-11 12:44 GMT+02:00 Christian Sacher <notifications@github.com>:
