### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Verox-** [headswe/Swifty#36]
System.IO.FileNotFoundException  at System.Drawing.Text.PrivateFontCollection.AddFontFile(String filename)
   at SwiftUpdater.Settings.LoadSettings() in h:\Development\C#\Arma\AddonLoader\SwiftUpdater\SwiftUpdater\Settings.cs:line 125

Call stack
SwiftUpdater.Settings.LoadSettings():125
SwiftUpdater.Program.Main():30

Exception message: File not found: null

Windows 7
Crashing since yesterday.

Program starts, no UI appears then silently exits after about 5 seconds. I had to race against it to attach the debugger...

**Comment by headswe** [comment]
Was issue with window 7 not support OTF font format
Fixed in 1.0.7.7
Reinstalled required if your application has been bricked.
