### ISSUE TITLE
Teamspeak autocopy - doesn't seem to work

### ISSUE THREAD

**Issue by Sniperhid** [headswe/Swifty#38]
I have noticed for several first time users that swifty doesn't copy the ACRE2 plugin. The tickbox is ticked but it isn't auto copying :/

**Comment by headswe** [comment]
Rewrote it for 1.0.8.1

**Comment by headswe** [comment]
??

**Comment by Sniperhid** [comment]
We'll test this thoroughally on friday. Head also could you make it so that it only restarts teamspeak in the case where it has updated a mod that uses the teamspeak folder?

**Comment by beaar** [comment]
Please warn the user before restarting TS3

**Comment by Sniperhid** [comment]
So after testing on friday and moving to a newer build of ACRE2, it seemed to copy it for at least 50% of Swifty users, though I know of 3 people who it did not autocopy for.

**Comment by headswe** [comment]
I rewrote this for 0.6 or 0.7, so it should be way less prone to failure.

**Comment by Nixxen** [comment]
Had this happen on version 2.0.0.9
Autocopy was ticked. No teamspeak plugin installed. Running Windows 10 pro x64.

(On an unrelated note; Repo update is is getting blocked by Bitdefender firewall even when added to the exceptions list. Running program as admin "bypasses" the firewall. Not sure why that is)
