### ISSUE TITLE
Launching Arma 3 with Battleye Enabled.

### ISSUE THREAD

**Issue by ryanparsons7** [headswe/Swifty#42]
The program launches Arma3.exe therefore requiring a restart upon joining a Battleye enabled server

**Comment by evromalarkey** [comment]
-useBE this should do the trick

**Comment by Sniperhid** [comment]
Perhaps a 'Battle-eye enabled' tickbox might work well here

**Comment by jonpas** [comment]
Checkboxes like ArmA3Sync has for some more settings than BattlEye wouldn't be bad either, but I don't want to make a new issue for that in case it's out of scope for this project.

**Comment by headswe** [comment]
I will add a option to the Repo.xml to enforce battle eye launch :)

**Comment by evromalarkey** [comment]
so what should we add into repo.xml?

**Comment by headswe** [comment]
´<ForceBattleEye>true</ForceBattleEye>
