### ISSUE TITLE
Swifty Updater cannot find path

### ISSUE THREAD

**Issue by Bullace** [headswe/Swifty#53]
While starting Swifty it automatically tried to update, during this process cmd.exe showed up, flashed some text and eventually ended with the error `Windows cannot find 'C:\Program'. Make sure you've typed the name correctly, then try again.`. After hitting close on the error message nothing happened. Re-opening Swifty works as it seems to have updated anyway. My Swifty is installed in the default directory which is `C:\Program Files (x86)\Swifty`.

**Comment by dslyecxi** [comment]
Saw this the first time I installed it today when it attempted to run after the install had completed.

**Comment by headswe** [comment]
Yes, recently introduced due to a pair of missing quotes.

Will be fixed in the 2.0.0.5

**Comment by headswe** [comment]
Fixed.
