### ISSUE TITLE
Swifty crashing when changing temp folder

### ISSUE THREAD

**Issue by nikolauska** [headswe/Swifty#54]
Unfortunately no additional error info, just normal "Swifty has stopped working" from windows

I was able to recreate this with these steps:
- start download
- allow it to download couple files 
- cancel download 
- change temp folder

**Comment by headswe** [comment]
Anything else you can glean from this?

**Comment by nikolauska** [comment]
Added steps to recreate crashing

**Comment by headswe** [comment]
This doesn't seem related to temp folder per say but i fixed another crash bug that i replicated using the method above.
