### ISSUE TITLE
Swifty - Patcher stuck/stopped/crash

### ISSUE THREAD

**Issue by headswe** [headswe/Swifty#56]
Please more info.

**Comment by dslyecxi** [comment]
Hung while patching (2 of 4), log is:
http://pastebin.com/Uf3ttCaf

**Comment by Sniperhid** [comment]
@headswe Lines 32-39 in the log reference an IO exception, might be the cause of it being hung?

**Comment by headswe** [comment]
Yes, i know why!

**Comment by headswe** [comment]
I think i know why the issue is here and i think i got it fixed. please reopen if it shows up again in 2.0.0.5
