### ISSUE TITLE
[Bug] Strange Behaviour - Option to Update Repo with no Changes?

### ISSUE THREAD

**Issue by Sniperhid** [headswe/Swifty#57]
I suspect something weird is happening in the new version today. Server side all I did was update the server to the RHS 0.3.9.1 hotfix. Also Swifty got an update today.

After updating my repos and restarting swifty I am greeted with the repo wanting an update?
https://gyazo.com/36050d2bd39212df57cd3e02c7a22b4e
I then get an info page which is blank
https://gyazo.com/a40e2519154f459e76e785b679bc3d8b 
I can click continue
https://gyazo.com/90cfa43990c27d6b851351911c97bf0c

**Comment by headswe** [comment]
This is most likely related to the optimizations i did the other day.

**Comment by headswe** [comment]
Found it, i had flipped the arugments into one function. Fixed for 2.0.0.5
