### ISSUE TITLE
More Info for User

### ISSUE THREAD

**Issue by Sniperhid** [headswe/Swifty#59]
Having more of an indicator as to what Swifty is doing and the progress, will greatly help users appreciate that Swifty hasn't crashed and is responsive. Ideally any operation that could take longer a second or two should report that it is doing something and anything more than 4-5 seconds should have a progress bar.

In particular displaying some progress/indication when it is doing the following would be ideal:
1) During a full patch - When it is starting to patch, it reads/scans all the hpd files, this process typically takes quite a while, but no update is shown to the user. Not quite sure what it is doing here.
2) When a mod is being being patched during 'patching', it just says patching addon: X/Y, for some large mods (e.g. AIA-TP) this can take quite a while. Displaying progress of the patching may be helpeful

**Comment by nikolauska** [comment]
There could info about what file is currently being patched for example

**Comment by Kllrt** [comment]
I agree with this, also I'd like some kind of window where I can see what it does when it's doing (which file) "Recheck".

**Comment by headswe** [comment]
Unlikely to add this until at the moment because how the back-end is built.

The new back-end already has the feature to more in depth monitor the process of patching.
