### ISSUE TITLE
Repo error message 530 does not reset.

### ISSUE THREAD

**Issue by Verox-** [headswe/Swifty#65]
Bug - Minor - GUI

Steps to reproduce:
1. Incorrectly set up a repo with an incorrect username/password
2. Attempt to use the repo, it will give the error 530: Not logged in.
3. Fix the incorrect username/password.
4. Attempt to use the repo again, it will still show the same error message in the hover tooltip, it will continue to show the error after the current operation has finished (at least on a brand-new repo setup.)

**Comment by headswe** [comment]
Fixed
