### ISSUE TITLE
Can open installer without datapackage being present.

### ISSUE THREAD

**Issue by lithiumfox** [headswe/Swifty#68]
Installing on Windows 10, Ran as Administrator

Installing to C:\Program Files (x86)\Swifty

Swifty Installer just says "Doing Shit" and lets you click next without installing any files.

**Comment by Fusselwurm** [comment]
did you unpack the zip file first, before exectuing the exe ? (not saying its no bug, swifty should check for data file being present)

**Comment by lithiumfox** [comment]
Ah. The readme didn't make it clear that the data file was necessary! Thought we only needed the installer which is typical with many applications! My bad! :)
