### ISSUE TITLE
Cannot point repo to subfolder on FTP server

### ISSUE THREAD

**Issue by Amuff1n** [headswe/Swifty#74]
Attempting to set the address of a repo to anything other than the bare address of the server is considered an invalid address. This means that the repo can only be located on the root folder of the FTP server. 

It'd be beneficial if Swifty could have a repo address point to a subfolder, e.g. having the repo hosted on ipaddress/subfolder/subfolder. Arma3Sync has this capability and the lack of this feature is holding me and my group from switching.

**Comment by Sniperhid** [comment]
Whilst this isn't a fix, there are still methods to make it work in the meanwhile.

The alternative options for now are to use HTTP which is faster (though not behind a login wall). Or to make a new FTP account where the root folder of that account is the subfolder for the repo, every separate repo would then need its own account. Perhaps not ideal, but this does work.

**Comment by headswe** [comment]
Exists in 2.1.0.8
