### ISSUE TITLE
Mod subfolders

### ISSUE THREAD

**Issue by jonpas** [headswe/Swifty#77]
Example repo structure:
```
swifty_tac_core/tac_mods/@CBA_A3
swifty_tac_core/tac_mods/@ace
swifty_tac_core/tac_packs/@hlcmods
swifty_tac_core/repo.png
swifty_tac_core/repo.xml
```

In the `Repository -> Mods` where the repository's mods are listed, the following shows up under `Preset addons`:
`<checkbox> swifty_tac_core`

When launching the game with that repository, it loads the `swifty_tac_core` mod, which is obviously not a mod.

**Comment by Sniperhid** [comment]
What address are you putting in the repo settings in Swifty? It seems like you may be doing DOMAIN.POSTFIX rather than DOMAIN.POSTFIX/swifty_tac_core/

Our mod subfolder for http seems to work fine.

**Comment by jonpas** [comment]
You mean client settings in Swifty when adding the repository? If so it is correct, any other fails to get repository info.

I updated the folder structure above to be more precise, we use 2 level subfolders. But moving eg. `@CBA_A3` and removing the 2 level subfolders doesn't fix it either, still only `swifty_tac_core` "mod" shows up and is used to launch the game.

Could it be a problem with `ServerAddress` in repo.xml? How should that be set, I guess pointing to the directory repo.xml is in? A URL from outside (eg. accessed by a browser)?

**Comment by Sniperhid** [comment]
I see now, at present swifty isnt designed to run with these sub-mod collections and is presently out of scope. If ypur intention is for users to have mods for different servers at our group we have separate repos for different server modpacks.

**Comment by jonpas** [comment]
That's not our intention, we simply keep it in sub-folders to keep it organized. If it's out of scope that's fine of course.

**Comment by headswe** [comment]
I have no plan to support this at the moment.
