### ISSUE TITLE
Installer does not check if .NET is installed - Installer hangs at "Doing shit..."

### ISSUE THREAD

**Issue by funar** [headswe/Swifty#81]
The installer will hang at "Doing shit..." if .NET is not installed on the PC.

Since .NET is not installed by default on Windows 8/8.1 & Windows 10, it may be desirable to trigger Windows to ask the user to add the feature.

**Comment by headswe** [comment]
Unlikely this is the cause since without NET you wouldn't be able to start it.

**Comment by funar** [comment]
We were able to duplicate the issue last night on a machine lacking .NET.  After installing .NET, the installer was able to get past that point and finish the installation.  Furthermore, removing .NET caused the installer to hang in the same place.

**Comment by sthorshaug** [comment]
This could happen if the installed version of .NET is too old compared to the version required by Swifty. I'm not saying this is the reason, but it could be if the installer calls a class or method which does not exist and the exception is caught but not handled properly.

**Comment by headswe** [comment]
Yes most likely 

-----Original Message-----
