### ISSUE TITLE
Option to trust self signed SSL certificate

### ISSUE THREAD

**Issue by ghost** [headswe/Swifty#83]
I would like an option in the repository configuration to trust self signed certificates. 
This would allow us to communicate with the repository server without showing the password and without buying a ssl certificate.

If we disable the ssl communication everything works. When communicating over ssl we get an error message that a trusted ssl/tls connection could not be made.

**Comment by headswe** [comment]
I assume this is FTP.

I'd really advise using FTP at all, the backend for FTP that i use is very lackluster ;)

**Comment by vanten** [comment]
We're using HTTP but we'd like to use HTTPS instead with self signed certificates (To hide the password).

**Comment by Dahlgren** [comment]
You can use https://letsencrypt.org/ to get a free valid SSL certificate
