### ISSUE TITLE
Fails to launch after install

### ISSUE THREAD

**Issue by EagleEye-FA** [headswe/Swifty#85]
Installer works fine but on windows 8.1 the Launch Swifty checkbox must point to the wrong path, because I get a "Windows cannot find swifty.exe" error.

**Comment by Sniperhid** [comment]
Did you install Swifty to the default install path?

**Comment by EagleEye-FA** [comment]
Sorry should have included that alright. Its installed to: C:\Program Files (x86)\Swifty
Which I believe is default. My mods and arma and temp folder are in E:\
Also, this was a reinstall, so my settings and such were saved from an old install. Can't confirm if the path changed, but I dont think it did.

**Comment by ImperialAlex** [comment]
Repro'd with v2.0.0.8 installer 
http://imgur.com/y0xhZFc

**Comment by headswe** [comment]
Fixed in 2.1.0.8.
