### ISSUE TITLE
InvalidOperationException when using patchcreator

### ISSUE THREAD

**Issue by bux578** [headswe/Swifty#87]
Using the sample xml file: https://gist.github.com/headswe/695dd62dc018bdac347a

I get the following error:
![image](https://cloud.githubusercontent.com/assets/1235520/11014632/e94b1e60-853f-11e5-983e-06beb9e04e0e.png)

Changing `<ForceBattleEye>False</ForceBattleEye>` to `<ForceBattleEye>false</ForceBattleEye>` (lowercase false) resolved the issue.

**Comment by headswe** [comment]
Fixed in 2.1.0.8
