### ISSUE TITLE
Patchreator crashes

### ISSUE THREAD

**Issue by BreberaCZ** [headswe/Swifty#89]
Hi
Everytime when I try to create my own Swifty repo, I got this problem: 
When Patchreator starts processing mods files, everything is okay, my second folder is filled with the mods , seems okay, mods size in outputfolder is the same as in input, so you might think where is the problem. It crashes everytime its finished with the mods, but I got nothing like xml or something like that in output, so I cannot start my repo. It only says this: 
Files, that describe problem. 
  C:\Users\user1\AppData\Local\Temp\WER453D.tmp.WERInternalMetadata.xml
  C:\Users\user1\AppData\Local\Temp\WER7F60.tmp.appcompat.txt
  C:\Users\user1\AppData\Local\Temp\WER915B.tmp.mdmp
(this files don't even exist when I look there ) 
Even when I do it on my own pc not on server. 
Help please, I would really like to use this as the other launchers as pw6 or sync really sucks.

**Comment by headswe** [comment]
Patchcreator has been rewritten in the new version. please take a look using it and report again if you still have issues.

**Comment by BreberaCZ** [comment]
Tried, but I cannot even target the patchreator.exe . even if the path is good. Any advice ?

**Comment by headswe** [comment]
No idea, friend get me some screenshots?

**Comment by BreberaCZ** [comment]
okay, the path is now okay, got just little problem there, however, still cannot run patchreator. The cmd only displays for one se c and the shutds down, and doesn't start. The bat file is written good. I think.

**Comment by headswe** [comment]
Post the bat file?

**Comment by BreberaCZ** [comment]
btw is it just me or we cannot choose the folder where will swifty be installed ? 
here is video with my problem. https://www.youtube.com/watch?v=wv0TPToY_qM&feature=youtu.be

**Comment by BreberaCZ** [comment]
yea btw my bat : start C:\Swifty\app-2.1.0.8\patchcreator.exe -r "C:\FTP\mods" "C:\FTP\smods"

**Comment by headswe** [comment]
Try putting your bat in the same folder as patchcreator.exe

**Comment by BreberaCZ** [comment]
nope doesn't work. Says somenithg about missing patchreatorCMD, but I got it in that folder.

**Comment by BreberaCZ** [comment]
Yea, it seems it starts working, but it immediately crashes down, and seems it wont start again until the server is restarted

**Comment by headswe** [comment]
It sadly seems it on your end?, maybe check that nothing is blocking it and that you are using latest NET.

**Comment by BreberaCZ** [comment]
Yea, I got latest NET framework and the path is fine.

**Comment by BreberaCZ** [comment]
Okay its sad but, we wont be able to use swifty thanks to his bug that seems like it wont be fixed. Sad, now I have to teach like 200 ppl how to use old sync.
