### ISSUE TITLE
[Feature request] Copy userconfig/acre plugins automatically

### ISSUE THREAD

**Issue by Sniperhid** [headswe/Swifty#9]
Would be great to have support to automatically copy things to the userconfig folder. Automatic copying of ACRE/TFR dlls would be cool (First check that the dlls are different, then tell user to close teamspeak :) (PWS does a really bad job of informing the user of this, and throws a 'process running' error or something like that))!

**Comment by headswe** [comment]
Already implemented the userconfig part of this today but our 1tac repo has
the six updater userconfig (archived) and this needs to be corrected


2015-03-15 16:22 GMT+01:00 Sniperhid <notifications@github.com>:

**Comment by Sniperhid** [comment]
Implemented already.
