### ISSUE TITLE
Support optional mods?

### ISSUE THREAD

**Issue by alterscape** [headswe/Swifty#92]
Would the dev team be willing to support optional mods in repos? Use-case here is eg: dynasound or JSRS_Lite -- mods that some players want, and don't alter the MP experience too much, but are too big to make a mandatory download and/or there are multiple options available, and users only want to run one at a time? It seems to be possible to deselect mods from the repo settings, but it would be nice if one could specify in the repo.xml "make this mod deselected by default, but allow users to select it if they want."

**Comment by headswe** [comment]
Yes, but unsure when i can get to this.

**Comment by headswe** [comment]
Done in V3!
