### ISSUE TITLE
Issue with delta patched pbos.

### ISSUE THREAD

**Issue by headswe** [headswe/Swifty#95]
"Data file too short 'C:\Program Files (x86)\Steam\Steamapps\common\Arma 3\ OLYMPUS\@mcc_sandbox\addons\mcc_sandbox_mod.pbo'. Expected 22056276 B, got 22012434 B"

**Comment by headswe** [comment]
I've not been able to replicate this bug.

**Comment by nikolauska** [comment]
This issue appeared for one guy on our community. 

How I believe this error occured (atleast for him):
1. He updated from 2.0 to 2.1
2. Our repository had update that changed ace3 from version 3.4.0 to 3.4.1 before he updated
3. His swifty updates ace3
4. Ace3 pbo's started to show this error.

**Comment by headswe** [comment]
Duplicate to #107
