### ISSUE TITLE
Patchcreator no longer shows what it does

### ISSUE THREAD

**Issue by nikolauska** [headswe/Swifty#97]
#### Swifty version
2.1.1.0

#### Patchcreator version
0.0.0.8 

#### Description
Patchcreator no longer shows what file or mod is being handled currently making debugging issues with repository a lot harder. I believe most of the people handling repositories like having information as much as possible of what happens with repository creation or at least we would like that.

**Comment by headswe** [comment]
Fixed in 0.0.0.9.
